declare module "eslint-plugin-react-refresh"
declare module "eslint-plugin-unused-imports"
declare module "eslint-plugin-tailwindcss"
declare module "eslint-plugin-react-google-translate"
declare module "@eslint-community/eslint-plugin-eslint-comments"
